# Generated by Django 3.2.8 on 2022-03-06 14:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('name', models.CharField(error_messages={'unique': '同一の商品が既に登録されています'}, max_length=100, unique=True, verbose_name='商品名')),
                ('description', models.CharField(max_length=3000, verbose_name='商品説明')),
                ('price', models.PositiveIntegerField(verbose_name='価格')),
                ('situation', models.BooleanField(verbose_name='販売状態')),
                ('stock', models.PositiveIntegerField(verbose_name='在庫数')),
                ('image', models.ImageField(upload_to='shop/product_image/images/', verbose_name='サムネイル')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryParent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('name', models.CharField(error_messages={'unique': '同一のカテゴリーが既に登録されています'}, max_length=20, unique=True, verbose_name='カテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('image', models.ImageField(upload_to='shop/product_image/images/', verbose_name='商品画像')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='対象商品')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryChild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('name', models.CharField(error_messages={'unique': '同一の商品が既に登録されています'}, max_length=100, unique=True, verbose_name='カテゴリー名')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productcategoryparent', verbose_name='カテゴリー')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.productcategorychild', verbose_name='カテゴリ'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('liked', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='リスト名')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='商品')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='お問い合わせ日時')),
                ('name', models.CharField(max_length=30, verbose_name='名前')),
                ('email', models.EmailField(max_length=200, verbose_name='メールアドレス')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('contents', models.CharField(max_length=3000, verbose_name='お問い合わせ内容')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='カート追加日時')),
                ('amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='商品の個数')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='カート所有者')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'name')},
        ),
    ]
